### ISSUE TITLE
Fixes, benchmarks, and failing tests for strings with non-numerics

### ISSUE THREAD

**Issue by daved** [dineshappavoo/basex#2]
Please look over these commits.  https://github.com/daved/basex/tree/alt/cleanup0

I didn't do any work on the algorithms.  I can look into that later if you'd like the contribution.  Make any changes you'd like unless you would rather me make a pull request for everything.  Criticisms are welcomed.

**Comment by dineshappavoo** [comment]
@daved - Thank you very much for sharing this. I really appreciate your contribution and that makes the package elegant.

For the dictionary, I wanted to make it as a generic set of characters. I mean, user can choose the set of characters they want. That's why I kept 4 options. I wanted to make it as an enhancement. 

It is your contribution. So make a pull request
